=== giellatekno/webpipelines/client/locale_data/data/cgi-translations.dtd
<!-- Translation xml files for the cgi-bin programs -->
<!ELEMENT content (title|place|copyright|introduction|introduction_p2|usage|example|instruction|selection|charset|input|noresult|otherforms|endtext|end|grammar)*>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title tool CDATA #IMPLIED>
<!ATTLIST title lang CDATA #IMPLIED>

<!ELEMENT place (#PCDATA)>

<!ELEMENT copyright (#PCDATA)>
<!ATTLIST copyright lang CDATA #IMPLIED>

<!ELEMENT introduction (#PCDATA)>
<!ATTLIST introduction tool CDATA #IMPLIED>
<!ATTLIST introduction lang CDATA #IMPLIED>
<!ATTLIST introduction type CDATA #IMPLIED>

<!ELEMENT introduction_p2 (#PCDATA)>
<!ATTLIST introduction_p2 tool CDATA #IMPLIED>
<!ATTLIST introduction_p2 lang CDATA #IMPLIED>

<!ELEMENT usage (#PCDATA)>
<!ATTLIST usage lang CDATA #IMPLIED>

<!ELEMENT example (#PCDATA)>
<!ATTLIST example lang CDATA #IMPLIED>
<!ATTLIST example tool CDATA #IMPLIED>

<!ELEMENT instruction (#PCDATA)*>
<!ATTLIST instruction tool CDATA #IMPLIED>

<!ELEMENT selection (select+)>
<!ATTLIST selection tool CDATA #IMPLIED>

    <!ELEMENT select (#PCDATA)>
    <!ATTLIST select type CDATA #IMPLIED>
    <!ATTLIST select tool CDATA #IMPLIED>
    <!ATTLIST select lang CDATA #IMPLIED>

<!ELEMENT charset (#PCDATA)>

<!ELEMENT input (#PCDATA)>
<!ATTLIST input type CDATA #IMPLIED>

<!ELEMENT noresult (#PCDATA)>
<!ATTLIST noresult tool CDATA #IMPLIED>

<!ELEMENT otherforms (#PCDATA)>
<!ATTLIST otherforms tool CDATA #IMPLIED>

<!ELEMENT endtext (#PCDATA)>

<!ELEMENT end (#PCDATA)>
<!ATTLIST end lang CDATA #IMPLIED>
<!ATTLIST end tool CDATA #IMPLIED>

<!ELEMENT grammar (pos+)>

    <!ELEMENT pos (#PCDATA)>
    <!ATTLIST pos type CDATA #IMPLIED>

=== giellatekno/webpipelines/client/locale_data/data/cgi-fin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document PUBLIC "-//UIT//DTD CGI TRANSLATIONS V1.0//EN" "https://giellatekno.uit.no/dtd/cgi-translations.dtd">
<content>


<title tool="analyze" lang="bxr" >Buriatin kielen analyysiohjelmat</title>
<title tool="analyze" lang="ciw" >Ojibwen kielen analyysiohjelmat</title>
<title tool="analyze" lang="cor" >Kornin kielen kielen analyysiohjelmat</title>
<title tool="analyze" lang="crk" >Plains cree-kielen kielen analyysiohjelmat</title>
<title tool="analyze" lang="est" >Viron kielen analyysiohjelmat</title>
<title tool="analyze" lang="evn" >Evenkin kielen analyysiohjelmat</title>
<title tool="analyze" lang="fao" >Fäärin kielen analyysiohjelmat</title>
<title tool="analyze" lang="fin" >Suomen kielen analyysiohjelmat</title>
<title tool="analyze" lang="fit" >Meänkielen analyysiohjelmat</title>
<title tool="analyze" lang="fkv" >Kveenin kielen analyysiohjelmat</title>
<title tool="analyze" lang="gle" >Iirin kielen analyysiohjelmat</title>
<title tool="analyze" lang="hdn" >Pohjoishaidan kielen analyysiohjelmat</title>
<title tool="analyze" lang="ipk" >Inupiakin kielen analyysiohjelmat</title>
<title tool="analyze" lang="izh" >Inkerin kielen analyysiohjelmat</title>
<title tool="analyze" lang="kal" >Grönlannin kielen analyysiohjelmat</title>
<title tool="analyze" lang="kca" >Hantin kielen analyysiohjelmat</title>
<title tool="analyze" lang="kpv" >Komin kielen analyysiohjelmat</title>
<title tool="analyze" lang="liv" >Liivin kielen analyysiohjelmat</title>
<title tool="analyze" lang="mdf" >Mokšan kielen analyysiohjelmat</title>
<title tool="analyze" lang="mhr" >Niitymarin kielen analyysiohjelmat</title>
<title tool="analyze" lang="mns" >Mansin kielen analyysiohjelmat</title>
<title tool="analyze" lang="mrj" >Vuorimarin kielen analyysiohjelmat</title>
<title tool="analyze" lang="myv" >Ersän kielen analyysiohjelmat</title>
<title tool="analyze" lang="nio" >Nganasanin kielen analyysiohjelmat</title>
<title tool="analyze" lang="olo" >Livvin kielen analyysiohjelmat</title>
<title tool="analyze" lang="rmf" >Suomen romanikielen analyysiohjelmat</title>
<title tool="analyze" lang="rus" >Venäjän kielen analyysiohjelmat</title>
<title tool="analyze" lang="sje" >Piiitimen kielen analyysiohjelmat</title>
<title tool="analyze" lang="sma" >Eteläsaamen kielen analyysiohjelmat</title>
<title tool="analyze" lang="sme" >Pohjoissaamen kielen analyysiohjelmat</title>
<title tool="analyze" lang="smj" >Luulajansaamen kielen analyysiohjelmat</title>
<title tool="analyze" lang="smn" >Inarinsaamen kielen analyysiohjelmat</title>
<title tool="analyze" lang="sms" >Koltansaamen kielen analyysiohjelmat</title>
<title tool="analyze" lang="som" >Somalin kielen analyysiohjelmat</title>
<title tool="analyze" lang="udm" >Udmurtin kielen analyysiohjelmat</title>
<title tool="analyze" lang="vep" >Vepsän kielen analyysiohjelmat</title>
<title tool="analyze" lang="vro" >Võron kielen analyysiohjelmat</title>
<title tool="analyze" lang="vot" >Vatjan kielen analyysiohjelmat</title>
<title tool="analyze" lang="yrk" >Nenetsin kielen analyysiohjelmat</title>


<title tool="generate" lang="bxr" >Luo buriatin kielen sanamuotoja</title>
<title tool="generate" lang="ciw" >Luo ojibwen kielen sanamuotoja</title>
<title tool="generate" lang="cor" >Luo kornin kielen kielen sanamuotoja</title>
<title tool="generate" lang="crk" >Luo plains cree-kielen kielen sanamuotoja</title>
<title tool="generate" lang="est" >Luo viron kielen sanamuotoja</title>
<title tool="generate" lang="evn" >Luo evenkin kielen sanamuotoja</title>
<title tool="generate" lang="fao" >Luo fäärin kielen sanamuotoja</title>
<title tool="generate" lang="fin" >Luo suomen kielen sanamuotoja</title>
<title tool="generate" lang="fit" >Luo meänkielen sanamuotoja</title>
<title tool="generate" lang="fkv" >Luo kveenin kielen sanamuotoja</title>
<title tool="generate" lang="gle" >Luo iirin kielen sanamuotoja</title>
<title tool="generate" lang="hdn" >Luo pohjoishaidan kielen sanamuotoja</title>
<title tool="generate" lang="ipk" >Luo inupiakin kielen sanamuotoja</title>
<title tool="generate" lang="izh" >Luo inkerin kielen sanamuotoja</title>
<title tool="generate" lang="kal" >Luo grönlannin kielen sanamuotoja</title>
<title tool="generate" lang="kca" >Luo hantin kielen sanamuotoja</title>
<title tool="generate" lang="kpv" >Luo komin kielen sanamuotoja</title>
<title tool="generate" lang="liv" >Luo liivin kielen sanamuotoja</title>
<title tool="generate" lang="mdf" >Luo mokšan kielen sanamuotoja</title>
<title tool="generate" lang="mhr" >Luo niitymarin kielen sanamuotoja</title>
<title tool="generate" lang="mns" >Luo mansin kielen sanamuotoja</title>
<title tool="generate" lang="mrj" >Luo vuorimarin kielen sanamuotoja</title>
<title tool="generate" lang="myv" >Luo ersän kielen sanamuotoja</title>
<title tool="generate" lang="nio" >Luo nganasanin kielen sanamuotoja</title>
<title tool="generate" lang="olo" >Luo livvin kielen sanamuotoja</title>
<title tool="generate" lang="rus" >Luo venäjän kielen sanamuotoja</title>
<title tool="generate" lang="sje" >Luo piiitimen kielen sanamuotoja</title>
<title tool="generate" lang="sma" >Luo eteläsaamen kielen sanamuotoja</title>
<title tool="generate" lang="sme" >Luo pohjoissaamen kielen sanamuotoja</title>
<title tool="generate" lang="smj" >Luo luulajansaamen kielen sanamuotoja</title>
<title tool="generate" lang="smn" >Luo inarinsaamen kielen sanamuotoja</title>
<title tool="generate" lang="sms" >Luo koltansaamen kielen sanamuotoja</title>
<title tool="generate" lang="som" >Luo somalin kielen sanamuotoja</title>
<title tool="generate" lang="udm" >Luo udmurtin kielen sanamuotoja</title>
<title tool="generate" lang="vep" >Luo vepsän kielen sanamuotoja</title>
<title tool="generate" lang="vro" >Luo võron kielen sanamuotoja</title>
<title tool="generate" lang="vot" >Luo vatjan kielen sanamuotoja</title>
<title tool="generate" lang="yrk" >Luo nenetsin kielen sanamuotoja</title>


<title tool="paradigm" lang="bxr" >Buriatin kielen taivutusparadigmat</title>
<title tool="paradigm" lang="ciw" >Ojibwen kielen taivutusparadigmat</title>
<title tool="paradigm" lang="cor" >Kornin kielen taivutusparadigmat</title>
<title tool="paradigm" lang="crk" >Plains cree-kielen taivutusparadigmat</title>
<title tool="paradigm" lang="est" >Viron kielen taivutusparadigmat</title>
<title tool="paradigm" lang="evn" >Evenkinin kielen taivutusparadigmat</title>
<title tool="paradigm" lang="fao" >Fäärin kielen taivutusparadigmat</title>
<title tool="paradigm" lang="fin" >Suomen kielen taivutusparadigmat</title>
<title tool="paradigm" lang="fit" >Meänkielen taivutusparadigmat</title>
<title tool="paradigm" lang="ipk" >Inupiakin kielen taivutusparadigmat</title>
<title tool="paradigm" lang="izh" >Inkerin kielen taivutusparadigmat</title>
<title tool="paradigm" lang="kal" >Grönlannin kielen taivutusparadigmat</title>
<title tool="paradigm" lang="kca" >Hantin kielen taivutusparadigmat</title>
<title tool="paradigm" lang="kpv" >Komin kielen taivutusparadigmat</title>
<title tool="paradigm" lang="liv" >Liivin kielen taivutusparadigmat</title>
<title tool="paradigm" lang="mdf" >Mokšan kielen taivutusparadigmat</title>
<title tool="paradigm" lang="mhr" >Niitymarin kielen taivutusparadigmat</title>
<title tool="paradigm" lang="mns" >Mansin kielen taivutusparadigmat</title>
<title tool="paradigm" lang="mrj" >Vuorimarin kielen taivutusparadigmat</title>
<title tool="paradigm" lang="myv" >Ersän kielen taivutusparadigmat</title>
<title tool="paradigm" lang="nio" >Nganasanin kielen taivutusparadigmat</title>
<title tool="paradigm" lang="olo" >Livvin kielen taivutusparadigmat</title>
<title tool="paradigm" lang="rus" >Venäjän kielen taivutusparadigmat</title>
<title tool="paradigm" lang="sje" >Piiitimen kielen taivutusparadigmat</title>
<title tool="paradigm" lang="sma" >Eteläsaamen kielen taivutusparadigmat</title>
<title tool="paradigm" lang="sme" >Pohjoissaamen kielen taivutusparadigmat</title>
<title tool="paradigm" lang="smj" >Luulajansaamen kielen taivutusparadigmat</title>
<title tool="paradigm" lang="smn" >Inarinsaamen kielen taivutusparadigmat</title>
<title tool="paradigm" lang="sms" >Koltansaamen kielen taivutusparadigmat</title>
<title tool="paradigm" lang="udm" >Udmurtin kielen taivutusparadigmat</title>
<title tool="paradigm" lang="vep" >Vepsän kielen taivutusparadigmat</title>
<title tool="paradigm" lang="vro" >Võron kielen taivutusparadigmat</title>
<title tool="paradigm" lang="vot" >Vatjan kielen taivutusparadigmat</title>
<title tool="paradigm" lang="yrk" >Nenetsin kielen taivutusparadigmat</title>


<title tool="placenames">Käännä paikannimet</title>



<!-- H1 -->



<place>Saame, Tromssan yliopisto</place>

<copyright lang="bxr">Copyright © Saami language technology project ja Jargal Badagarov</copyright>
<copyright lang="ciw">Copyright © Saami language technology project</copyright>
<copyright lang="crk">Copyright © Saami language technology project ja Albertan yliopisto</copyright>
<copyright lang="fao">Copyright © Saami language technology project</copyright>
<copyright lang="fin">Copyright © Saami language technology project ja Tommi Pirinen</copyright>
<copyright lang="fit">Copyright © Saami language technology project</copyright>
<copyright lang="fkv">Copyright © Saami language technology project</copyright>
<copyright lang="ipk">Copyright © Saami language technology project ja Oqaasileriffik</copyright>
<copyright lang="kal">Copyright © Saami language technology project ja Oqaasileriffik</copyright>
<copyright lang="kpv">Copyright © Saami language technology project ja Jack Rueter</copyright>
<copyright lang="mhr">Copyright © Saami language technology project ja Jorma Luutonen ja Arto Moisio</copyright>
<copyright lang="mns">Copyright © Saami language technology project</copyright>
<copyright lang="myv">Copyright © Saami language technology project ja Jack Rueter</copyright>
